### PR TITLE
Fix missed detection of single letter part names; Close #13

### LINKED ISSUE #13: `Physical Review. E` -> `Phys. Rev.,`
`E` is missing!

```py
>>> from pyiso4.ltwa import Abbreviate
>>> abbreviator = Abbreviate.create()
>>> abbreviator("Physical Review. E", remove_part=True)
'Phys. Rev.,'
```

### PR DESCRIPTION
**Pull request by klb2**
Fix the wrong classification of single letter part names, if the single letter is also a stopword.

Since "E" and "I" are in `stopwords.txt`, they were classified as `TokenType.STOPWORD` by the lexer, if not preceded by a word that is in `PARTS`. However, as described in #13, this can be a wrong classification.

With this commit, the lexer now considers symbols like `.` to also by an indicator of parts. Additionally, we need to change `IS_ORDINAL.match` to `IS_ORDINAL.fullmatch` to avoid false positives. (With `.match`, any partial match is evaluated to true, i.e., every word that starts with a capital letter is evaluated to true)

### CODE REVIEW

**Comment by pierre-24** [comment]
Sorry, I don't get why test do not launch themselves automatically. I probably need to put you in a list somewhere. However, as you can see, there is a mistake in your code.

Thank you for the `fullmatch`, I have to say that I did not know about that :)

**Comment by pierre-24** [comment]
Maybe you actually simply need to rebase your branch now that #12  is merged, thought :)

**Comment by klb2** [comment]
Yes, I think the issue was because #12 is merged.
I have updated the fork and you should now be able to also merge this.

**Comment by pierre-24** [comment]
Yep, thank you. I need to check one or two things, then I will to a release with all that :)

**Pull request merged**
